# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnlp.proto\x12\x17\x63om.scarike.gp.web.grpc\"\x1e\n\rRpcNlpRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\xa2\x02\n\x0eRpcNlpResponse\x12\x0e\n\x06status\x18\x01 \x01(\x11\x12\x0f\n\x07message\x18\x02 \x01(\t\x12@\n\x07keyword\x18\x03 \x03(\x0b\x32/.com.scarike.gp.web.grpc.RpcNlpResponse.Keyword\x1a\x8a\x01\n\x07Keyword\x12?\n\x04type\x18\x01 \x01(\x0e\x32\x31.com.scarike.gp.web.grpc.RpcNlpResponse.QueryType\x12\x0e\n\x06\x63\x65nter\x18\x02 \x01(\t\x12\x10\n\x08\x64istance\x18\x03 \x01(\x05\x12\x0f\n\x07poiCode\x18\x04 \x01(\x05\x12\x0b\n\x03key\x18\x05 \x01(\t\" \n\tQueryType\x12\t\n\x05POINT\x10\x00\x12\x08\n\x04LINE\x10\x01\x32n\n\rRpcNlpService\x12]\n\x08\x61nalysis\x12&.com.scarike.gp.web.grpc.RpcNlpRequest\x1a\'.com.scarike.gp.web.grpc.RpcNlpResponse\"\x00\x42/\n\x17\x63om.scarike.gp.web.grpcB\x10RpcNlpServiceApiH\x01P\x01\x62\x06proto3')



_RPCNLPREQUEST = DESCRIPTOR.message_types_by_name['RpcNlpRequest']
_RPCNLPRESPONSE = DESCRIPTOR.message_types_by_name['RpcNlpResponse']
_RPCNLPRESPONSE_KEYWORD = _RPCNLPRESPONSE.nested_types_by_name['Keyword']
_RPCNLPRESPONSE_QUERYTYPE = _RPCNLPRESPONSE.enum_types_by_name['QueryType']
RpcNlpRequest = _reflection.GeneratedProtocolMessageType('RpcNlpRequest', (_message.Message,), {
  'DESCRIPTOR' : _RPCNLPREQUEST,
  '__module__' : 'nlp_pb2'
  # @@protoc_insertion_point(class_scope:com.scarike.gp.web.grpc.RpcNlpRequest)
  })
_sym_db.RegisterMessage(RpcNlpRequest)

RpcNlpResponse = _reflection.GeneratedProtocolMessageType('RpcNlpResponse', (_message.Message,), {

  'Keyword' : _reflection.GeneratedProtocolMessageType('Keyword', (_message.Message,), {
    'DESCRIPTOR' : _RPCNLPRESPONSE_KEYWORD,
    '__module__' : 'nlp_pb2'
    # @@protoc_insertion_point(class_scope:com.scarike.gp.web.grpc.RpcNlpResponse.Keyword)
    })
  ,
  'DESCRIPTOR' : _RPCNLPRESPONSE,
  '__module__' : 'nlp_pb2'
  # @@protoc_insertion_point(class_scope:com.scarike.gp.web.grpc.RpcNlpResponse)
  })
_sym_db.RegisterMessage(RpcNlpResponse)
_sym_db.RegisterMessage(RpcNlpResponse.Keyword)

_RPCNLPSERVICE = DESCRIPTOR.services_by_name['RpcNlpService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.scarike.gp.web.grpcB\020RpcNlpServiceApiH\001P\001'
  _RPCNLPREQUEST._serialized_start=38
  _RPCNLPREQUEST._serialized_end=68
  _RPCNLPRESPONSE._serialized_start=71
  _RPCNLPRESPONSE._serialized_end=361
  _RPCNLPRESPONSE_KEYWORD._serialized_start=189
  _RPCNLPRESPONSE_KEYWORD._serialized_end=327
  _RPCNLPRESPONSE_QUERYTYPE._serialized_start=329
  _RPCNLPRESPONSE_QUERYTYPE._serialized_end=361
  _RPCNLPSERVICE._serialized_start=363
  _RPCNLPSERVICE._serialized_end=473
# @@protoc_insertion_point(module_scope)
