# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnlp.proto\x12\x1e\x63om.scarike.gp.web.common.grpc\"\x1e\n\rRpcNlpRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\xa3\x02\n\x0eRpcNlpResponse\x12\x0e\n\x06status\x18\x01 \x01(\x11\x12\x0f\n\x07message\x18\x02 \x01(\t\x12G\n\x07keyword\x18\x03 \x01(\x0b\x32\x36.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword\x1a\x84\x01\n\x07Keyword\x12\x46\n\x04type\x18\x01 \x01(\x0e\x32\x38.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType\x12\x0e\n\x06\x63\x65nter\x18\x02 \x01(\t\x12\x10\n\x08\x64istance\x18\x03 \x01(\x05\x12\x0f\n\x07poiCode\x18\x04 \x01(\x05\" \n\tQueryType\x12\t\n\x05POINT\x10\x00\x12\x08\n\x04LINE\x10\x01\x32|\n\rRpcNlpService\x12k\n\x08\x61nalysis\x12-.com.scarike.gp.web.common.grpc.RpcNlpRequest\x1a..com.scarike.gp.web.common.grpc.RpcNlpResponse\"\x00\x42\x36\n\x1e\x63om.scarike.gp.web.common.grpcB\x10RpcNlpServiceApiH\x01P\x01\x62\x06proto3')



_RPCNLPREQUEST = DESCRIPTOR.message_types_by_name['RpcNlpRequest']
_RPCNLPRESPONSE = DESCRIPTOR.message_types_by_name['RpcNlpResponse']
_RPCNLPRESPONSE_KEYWORD = _RPCNLPRESPONSE.nested_types_by_name['Keyword']
_RPCNLPRESPONSE_QUERYTYPE = _RPCNLPRESPONSE.enum_types_by_name['QueryType']
RpcNlpRequest = _reflection.GeneratedProtocolMessageType('RpcNlpRequest', (_message.Message,), {
  'DESCRIPTOR' : _RPCNLPREQUEST,
  '__module__' : 'nlp_pb2'
  # @@protoc_insertion_point(class_scope:com.scarike.gp.web.common.grpc.RpcNlpRequest)
  })
_sym_db.RegisterMessage(RpcNlpRequest)

RpcNlpResponse = _reflection.GeneratedProtocolMessageType('RpcNlpResponse', (_message.Message,), {

  'Keyword' : _reflection.GeneratedProtocolMessageType('Keyword', (_message.Message,), {
    'DESCRIPTOR' : _RPCNLPRESPONSE_KEYWORD,
    '__module__' : 'nlp_pb2'
    # @@protoc_insertion_point(class_scope:com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword)
    })
  ,
  'DESCRIPTOR' : _RPCNLPRESPONSE,
  '__module__' : 'nlp_pb2'
  # @@protoc_insertion_point(class_scope:com.scarike.gp.web.common.grpc.RpcNlpResponse)
  })
_sym_db.RegisterMessage(RpcNlpResponse)
_sym_db.RegisterMessage(RpcNlpResponse.Keyword)

_RPCNLPSERVICE = DESCRIPTOR.services_by_name['RpcNlpService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.scarike.gp.web.common.grpcB\020RpcNlpServiceApiH\001P\001'
  _RPCNLPREQUEST._serialized_start=45
  _RPCNLPREQUEST._serialized_end=75
  _RPCNLPRESPONSE._serialized_start=78
  _RPCNLPRESPONSE._serialized_end=369
  _RPCNLPRESPONSE_KEYWORD._serialized_start=203
  _RPCNLPRESPONSE_KEYWORD._serialized_end=335
  _RPCNLPRESPONSE_QUERYTYPE._serialized_start=337
  _RPCNLPRESPONSE_QUERYTYPE._serialized_end=369
  _RPCNLPSERVICE._serialized_start=371
  _RPCNLPSERVICE._serialized_end=495
# @@protoc_insertion_point(module_scope)
