# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nlp_pb2 as nlp__pb2


class RpcNlpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.analysis = channel.unary_unary(
                '/com.scarike.gp.web.common.grpc.RpcNlpService/analysis',
                request_serializer=nlp__pb2.RpcNlpRequest.SerializeToString,
                response_deserializer=nlp__pb2.RpcNlpResponse.FromString,
                )


class RpcNlpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def analysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RpcNlpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'analysis': grpc.unary_unary_rpc_method_handler(
                    servicer.analysis,
                    request_deserializer=nlp__pb2.RpcNlpRequest.FromString,
                    response_serializer=nlp__pb2.RpcNlpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.scarike.gp.web.common.grpc.RpcNlpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RpcNlpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def analysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.scarike.gp.web.common.grpc.RpcNlpService/analysis',
            nlp__pb2.RpcNlpRequest.SerializeToString,
            nlp__pb2.RpcNlpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
