// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nlp.proto

package com.scarike.gp.web.common.grpc;

/**
 * Protobuf type {@code com.scarike.gp.web.common.grpc.RpcNlpResponse}
 */
public  final class RpcNlpResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.scarike.gp.web.common.grpc.RpcNlpResponse)
    RpcNlpResponseOrBuilder {
  // Use RpcNlpResponse.newBuilder() to construct.
  private RpcNlpResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RpcNlpResponse() {
    status_ = 0;
    message_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RpcNlpResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            status_ = input.readSInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            Keyword.Builder subBuilder = null;
            if (keyword_ != null) {
              subBuilder = keyword_.toBuilder();
            }
            keyword_ = input.readMessage(Keyword.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(keyword_);
              keyword_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RpcNlpResponse.class, Builder.class);
  }

  /**
   * Protobuf enum {@code com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType}
   */
  public enum QueryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>POINT = 0;</code>
     */
    POINT(0),
    /**
     * <code>LINE = 1;</code>
     */
    LINE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>POINT = 0;</code>
     */
    public static final int POINT_VALUE = 0;
    /**
     * <code>LINE = 1;</code>
     */
    public static final int LINE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static QueryType valueOf(int value) {
      return forNumber(value);
    }

    public static QueryType forNumber(int value) {
      switch (value) {
        case 0: return POINT;
        case 1: return LINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<QueryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        QueryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<QueryType>() {
            public QueryType findValueByNumber(int number) {
              return QueryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RpcNlpResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final QueryType[] VALUES = values();

    public static QueryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private QueryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType)
  }

  public interface KeywordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
     */
    QueryType getType();

    /**
     * <code>string center = 2;</code>
     */
    String getCenter();
    /**
     * <code>string center = 2;</code>
     */
    com.google.protobuf.ByteString
        getCenterBytes();

    /**
     * <code>int32 distance = 3;</code>
     */
    int getDistance();

    /**
     * <code>int32 poiCode = 4;</code>
     */
    int getPoiCode();
  }
  /**
   * Protobuf type {@code com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword}
   */
  public  static final class Keyword extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword)
      KeywordOrBuilder {
    // Use Keyword.newBuilder() to construct.
    private Keyword(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Keyword() {
      type_ = 0;
      center_ = "";
      distance_ = 0;
      poiCode_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Keyword(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              center_ = s;
              break;
            }
            case 24: {

              distance_ = input.readInt32();
              break;
            }
            case 32: {

              poiCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Keyword.class, Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
     */
    public QueryType getType() {
      QueryType result = QueryType.valueOf(type_);
      return result == null ? QueryType.UNRECOGNIZED : result;
    }

    public static final int CENTER_FIELD_NUMBER = 2;
    private volatile Object center_;
    /**
     * <code>string center = 2;</code>
     */
    public String getCenter() {
      Object ref = center_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        center_ = s;
        return s;
      }
    }
    /**
     * <code>string center = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCenterBytes() {
      Object ref = center_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        center_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISTANCE_FIELD_NUMBER = 3;
    private int distance_;
    /**
     * <code>int32 distance = 3;</code>
     */
    public int getDistance() {
      return distance_;
    }

    public static final int POICODE_FIELD_NUMBER = 4;
    private int poiCode_;
    /**
     * <code>int32 poiCode = 4;</code>
     */
    public int getPoiCode() {
      return poiCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != QueryType.POINT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getCenterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, center_);
      }
      if (distance_ != 0) {
        output.writeInt32(3, distance_);
      }
      if (poiCode_ != 0) {
        output.writeInt32(4, poiCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != QueryType.POINT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getCenterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, center_);
      }
      if (distance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, distance_);
      }
      if (poiCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, poiCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Keyword)) {
        return super.equals(obj);
      }
      Keyword other = (Keyword) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getCenter()
          .equals(other.getCenter());
      result = result && (getDistance()
          == other.getDistance());
      result = result && (getPoiCode()
          == other.getPoiCode());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + CENTER_FIELD_NUMBER;
      hash = (53 * hash) + getCenter().hashCode();
      hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getDistance();
      hash = (37 * hash) + POICODE_FIELD_NUMBER;
      hash = (53 * hash) + getPoiCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Keyword parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Keyword parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Keyword parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Keyword parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Keyword parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Keyword parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Keyword parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Keyword parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Keyword parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Keyword parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Keyword parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Keyword parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Keyword prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword)
        KeywordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Keyword.class, Builder.class);
      }

      // Construct using com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        center_ = "";

        distance_ = 0;

        poiCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_descriptor;
      }

      public Keyword getDefaultInstanceForType() {
        return Keyword.getDefaultInstance();
      }

      public Keyword build() {
        Keyword result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Keyword buildPartial() {
        Keyword result = new Keyword(this);
        result.type_ = type_;
        result.center_ = center_;
        result.distance_ = distance_;
        result.poiCode_ = poiCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Keyword) {
          return mergeFrom((Keyword)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Keyword other) {
        if (other == Keyword.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getCenter().isEmpty()) {
          center_ = other.center_;
          onChanged();
        }
        if (other.getDistance() != 0) {
          setDistance(other.getDistance());
        }
        if (other.getPoiCode() != 0) {
          setPoiCode(other.getPoiCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Keyword parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Keyword) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
       */
      public QueryType getType() {
        QueryType result = QueryType.valueOf(type_);
        return result == null ? QueryType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
       */
      public Builder setType(QueryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.QueryType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private Object center_ = "";
      /**
       * <code>string center = 2;</code>
       */
      public String getCenter() {
        Object ref = center_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          center_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string center = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCenterBytes() {
        Object ref = center_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          center_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string center = 2;</code>
       */
      public Builder setCenter(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        center_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string center = 2;</code>
       */
      public Builder clearCenter() {
        
        center_ = getDefaultInstance().getCenter();
        onChanged();
        return this;
      }
      /**
       * <code>string center = 2;</code>
       */
      public Builder setCenterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        center_ = value;
        onChanged();
        return this;
      }

      private int distance_ ;
      /**
       * <code>int32 distance = 3;</code>
       */
      public int getDistance() {
        return distance_;
      }
      /**
       * <code>int32 distance = 3;</code>
       */
      public Builder setDistance(int value) {
        
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 distance = 3;</code>
       */
      public Builder clearDistance() {
        
        distance_ = 0;
        onChanged();
        return this;
      }

      private int poiCode_ ;
      /**
       * <code>int32 poiCode = 4;</code>
       */
      public int getPoiCode() {
        return poiCode_;
      }
      /**
       * <code>int32 poiCode = 4;</code>
       */
      public Builder setPoiCode(int value) {
        
        poiCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 poiCode = 4;</code>
       */
      public Builder clearPoiCode() {
        
        poiCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword)
    }

    // @@protoc_insertion_point(class_scope:com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword)
    private static final Keyword DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Keyword();
    }

    public static Keyword getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Keyword>
        PARSER = new com.google.protobuf.AbstractParser<Keyword>() {
      public Keyword parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Keyword(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Keyword> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Keyword> getParserForType() {
      return PARSER;
    }

    public Keyword getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>sint32 status = 1;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public String getMessage() {
    Object ref = message_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    Object ref = message_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYWORD_FIELD_NUMBER = 3;
  private Keyword keyword_;
  /**
   * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
   */
  public boolean hasKeyword() {
    return keyword_ != null;
  }
  /**
   * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
   */
  public Keyword getKeyword() {
    return keyword_ == null ? Keyword.getDefaultInstance() : keyword_;
  }
  /**
   * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
   */
  public KeywordOrBuilder getKeywordOrBuilder() {
    return getKeyword();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != 0) {
      output.writeSInt32(1, status_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (keyword_ != null) {
      output.writeMessage(3, getKeyword());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, status_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (keyword_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getKeyword());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RpcNlpResponse)) {
      return super.equals(obj);
    }
    RpcNlpResponse other = (RpcNlpResponse) obj;

    boolean result = true;
    result = result && (getStatus()
        == other.getStatus());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && (hasKeyword() == other.hasKeyword());
    if (hasKeyword()) {
      result = result && getKeyword()
          .equals(other.getKeyword());
    }
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasKeyword()) {
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeyword().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RpcNlpResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RpcNlpResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RpcNlpResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RpcNlpResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RpcNlpResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RpcNlpResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RpcNlpResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RpcNlpResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RpcNlpResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RpcNlpResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RpcNlpResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RpcNlpResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RpcNlpResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.scarike.gp.web.common.grpc.RpcNlpResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.scarike.gp.web.common.grpc.RpcNlpResponse)
      RpcNlpResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcNlpResponse.class, Builder.class);
    }

    // Construct using com.scarike.gp.web.common.grpc.RpcNlpResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      status_ = 0;

      message_ = "";

      if (keywordBuilder_ == null) {
        keyword_ = null;
      } else {
        keyword_ = null;
        keywordBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RpcNlpServiceApi.internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_descriptor;
    }

    public RpcNlpResponse getDefaultInstanceForType() {
      return RpcNlpResponse.getDefaultInstance();
    }

    public RpcNlpResponse build() {
      RpcNlpResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public RpcNlpResponse buildPartial() {
      RpcNlpResponse result = new RpcNlpResponse(this);
      result.status_ = status_;
      result.message_ = message_;
      if (keywordBuilder_ == null) {
        result.keyword_ = keyword_;
      } else {
        result.keyword_ = keywordBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RpcNlpResponse) {
        return mergeFrom((RpcNlpResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RpcNlpResponse other) {
      if (other == RpcNlpResponse.getDefaultInstance()) return this;
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasKeyword()) {
        mergeKeyword(other.getKeyword());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RpcNlpResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RpcNlpResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ ;
    /**
     * <code>sint32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>sint32 status = 1;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private Keyword keyword_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Keyword, Keyword.Builder, KeywordOrBuilder> keywordBuilder_;
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    public boolean hasKeyword() {
      return keywordBuilder_ != null || keyword_ != null;
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    public Keyword getKeyword() {
      if (keywordBuilder_ == null) {
        return keyword_ == null ? Keyword.getDefaultInstance() : keyword_;
      } else {
        return keywordBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    public Builder setKeyword(Keyword value) {
      if (keywordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        keyword_ = value;
        onChanged();
      } else {
        keywordBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    public Builder setKeyword(
        Keyword.Builder builderForValue) {
      if (keywordBuilder_ == null) {
        keyword_ = builderForValue.build();
        onChanged();
      } else {
        keywordBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    public Builder mergeKeyword(Keyword value) {
      if (keywordBuilder_ == null) {
        if (keyword_ != null) {
          keyword_ =
            Keyword.newBuilder(keyword_).mergeFrom(value).buildPartial();
        } else {
          keyword_ = value;
        }
        onChanged();
      } else {
        keywordBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    public Builder clearKeyword() {
      if (keywordBuilder_ == null) {
        keyword_ = null;
        onChanged();
      } else {
        keyword_ = null;
        keywordBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    public Keyword.Builder getKeywordBuilder() {
      
      onChanged();
      return getKeywordFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    public KeywordOrBuilder getKeywordOrBuilder() {
      if (keywordBuilder_ != null) {
        return keywordBuilder_.getMessageOrBuilder();
      } else {
        return keyword_ == null ?
            Keyword.getDefaultInstance() : keyword_;
      }
    }
    /**
     * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Keyword, Keyword.Builder, KeywordOrBuilder>
        getKeywordFieldBuilder() {
      if (keywordBuilder_ == null) {
        keywordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Keyword, Keyword.Builder, KeywordOrBuilder>(
                getKeyword(),
                getParentForChildren(),
                isClean());
        keyword_ = null;
      }
      return keywordBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.scarike.gp.web.common.grpc.RpcNlpResponse)
  }

  // @@protoc_insertion_point(class_scope:com.scarike.gp.web.common.grpc.RpcNlpResponse)
  private static final RpcNlpResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RpcNlpResponse();
  }

  public static RpcNlpResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RpcNlpResponse>
      PARSER = new com.google.protobuf.AbstractParser<RpcNlpResponse>() {
    public RpcNlpResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcNlpResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RpcNlpResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RpcNlpResponse> getParserForType() {
    return PARSER;
  }

  public RpcNlpResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

