// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nlp.proto

package com.scarike.gp.web.common.grpc;

public final class RpcNlpServiceApi {
  private RpcNlpServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scarike_gp_web_common_grpc_RpcNlpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tnlp.proto\022\036com.scarike.gp.web.common.g" +
      "rpc\"\036\n\rRpcNlpRequest\022\r\n\005query\030\001 \001(\t\"\243\002\n\016" +
      "RpcNlpResponse\022\016\n\006status\030\001 \001(\021\022\017\n\007messag" +
      "e\030\002 \001(\t\022G\n\007keyword\030\003 \001(\01326.com.scarike.g" +
      "p.web.common.grpc.RpcNlpResponse.Keyword" +
      "\032\204\001\n\007Keyword\022F\n\004type\030\001 \001(\01628.com.scarike" +
      ".gp.web.common.grpc.RpcNlpResponse.Query" +
      "Type\022\016\n\006center\030\002 \001(\t\022\020\n\010distance\030\003 \001(\005\022\017" +
      "\n\007poiCode\030\004 \001(\005\" \n\tQueryType\022\t\n\005POINT\020\000\022" +
      "\010\n\004LINE\020\0012|\n\rRpcNlpService\022k\n\010analysis\022-",
      ".com.scarike.gp.web.common.grpc.RpcNlpRe" +
      "quest\032..com.scarike.gp.web.common.grpc.R" +
      "pcNlpResponse\"\000B6\n\036com.scarike.gp.web.co" +
      "mmon.grpcB\020RpcNlpServiceApiH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scarike_gp_web_common_grpc_RpcNlpRequest_descriptor,
        new String[] { "Query", });
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_descriptor,
        new String[] { "Status", "Message", "Keyword", });
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_descriptor =
      internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_scarike_gp_web_common_grpc_RpcNlpResponse_Keyword_descriptor,
        new String[] { "Type", "Center", "Distance", "PoiCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
