// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nlp.proto

package com.scarike.gp.web.common.grpc;

public interface RpcNlpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scarike.gp.web.common.grpc.RpcNlpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   */
  String getQuery();
  /**
   * <code>string query = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
