// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nlp.proto

package com.scarike.gp.web.common.grpc;

public interface RpcNlpResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.scarike.gp.web.common.grpc.RpcNlpResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 status = 1;</code>
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
   */
  boolean hasKeyword();
  /**
   * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
   */
  RpcNlpResponse.Keyword getKeyword();
  /**
   * <code>.com.scarike.gp.web.common.grpc.RpcNlpResponse.Keyword keyword = 3;</code>
   */
  RpcNlpResponse.KeywordOrBuilder getKeywordOrBuilder();
}
